---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1

ignore: |
  .github/workflows
  renovate.json
  .git

exclude: |
  .git
  node_modules
  *.backup
